### ISSUE TITLE
state variable to add for snow redistribution

### ISSUE THREAD

**Issue by theobarnhart** [RHESSys/RHESSys#103]
Hi RHESSys team, 

I'm trying to use the -snowdistb flag with RHESSys5.19 and see that it requires a new state variable for each patch (from the documentation in the wiki). What should this variable be called? I've been digging through the source code and found `if (fabs(ltmp - NULLVAL) >= ONE)  patch[0].snow_redist_scale = ltmp;` in rhessys/tec/input_new_patch.c. Should the new variable in my template be snow_redist_scale?

Thanks!

Theo

**Comment by jschoate** [comment]
Hi Theo,
yes - you must add the state variable snow_redist_scale to your worldfile - it must be positioned immeadiatly after the state variable snowpack.energy_deficit within the patch level. 
you could add this state variable into the template then create your worldfile, or use something like an awk script to insert the new state variable snow_redist_scale into each patch of an existing worldfile. 

then when you run RHESSys, you have to add the -snowdistb flag to the command line to turn on snow redistribution. 

note on what it does and setting a value for this state variable:

for each day, and for each patch -  RHESSys will multiply the incoming snow (so the snow falling at the top of the canopy - which is a zone level state variable ) by this snow_redist_scale, thus we are assuming snow redistribution occurs as snow falls.

this means that in order to not generate additional incoming water - you need to make sure that the scale factor that you use average to 1 for each zone - so it is the users responsibility in assigning scale factors.

so for any zone:
sum( snow_redist_scale (for patch i) * area (for patch i) ) /  total
zone (area) must be equal to 1.0

Janet

**Comment by theobarnhart** [comment]
Thank you Janet! This is very helpful.

Is there a suggested range for the optional tolerance parameter passed on
the command line?

Thanks!

Theo

Theodore Barnhart
PhD Candidate
INSTAAR / Geography
University of Colorado
theodore.barnhart@colorado.edu
https://theobarnhart.github.io/

**Comment by theobarnhart** [comment]
Just to update before closing the issue, I got the -snowdistb flag to run by adding the snow_redist_scale variable as Janet instructed above. This did end up breaking LAIREAD when building my worldfile from a template in GRASS so I made a little work around. The trick is to make two worldfiles, one with the snow_redist_scale variable and another without, but with all the values from LAI read. Then I wrote a little python script to merge the two while preserving the snow_redist_scale variable. Script attached if anyone finds it useful.
[assimilate_lai.py.txt](https://github.com/RHESSys/RHESSys/files/925817/assimilate_lai.py.txt)
