### ISSUE TITLE
wordfile creation problems #2

### ISSUE THREAD

**Issue by koadean** [RHESSys/RHESSys#72]
Aloha again, we also not sure if we need the .def files for template creation. The template has a list of files as .def but there is no such files (or folder) installed with RHESSYS/GRASS. If we do, where can we download them from? Cheers

**Comment by jschoate** [comment]
koadean,
if you are creating your input files manually, then you do not need the .def files (definition files) in existence for the template, or to create the worldfile - but they do need to at least be listed at the top of the template, even if the actual files haven't been generated yet.
however, you will need the .def files and climate files to be in existence in order to run RHESSys. you can generate the definition files from the Parameter Database (https://github.com/RHESSys/ParamDB), and you will need to generate your own climate files.
Alternatively, you can use RHESSysWorkflows to create your definition and climate files along with your worldfile, flowtable, and tecfile.

**Comment by koadean** [comment]
Aloha jschoate, thanks for the advice. Cheers
