### ISSUE TITLE
Unsaturated/root zone drainage calculation inconsistencies

### ISSUE THREAD

**Issue by selimnairb** [RHESSys/RHESSys#77]
In RHESSys 5.20.0, we are seeing basin-scale daily values of unsat and root zone drainage that are ~1-2 orders of magnitude greater than they should be.  There appear to be a few problems with the calculation of unsaturated and/or root zone drainage.

First, in some cases, root zone (and unsat) drainage is calculated using [Ksat_0_v](https://github.com/RHESSys/RHESSys/blob/master/rhessys/cycle/patch_daily_F.c#L1849), but in others using Ksat_0, as in [here](https://github.com/RHESSys/RHESSys/blob/master/rhessys/cycle/patch_daily_F.c#L1879), [here](https://github.com/RHESSys/RHESSys/blob/master/rhessys/hydro/compute_subsurface_routing.c#L880), and [here](https://github.com/RHESSys/RHESSys/blob/master/rhessys/hydro/compute_subsurface_routing_hourly.c#L876).  It is not clear to me what is correct.

Second, in the above examples the value of Ksat passed into *compute_unsat_zone_drainage()* are all divided by 2.  Why is this done?

I need advice on what the right thing to do is for the first.  For the second, we need some text for the comments that describes the rationale for dividing Ksat by 2.  I will address both problems through a single branch and pull request that references this issue.

**Comment by selimnairb** [comment]
@naomitague @xiaoli-chen Could you please read this issue and advise?  Thanks.

**Comment by laurencelin** [comment]
It sounds like we will have to do another set of calibrations after this fix, right?

Laurence

**Comment by selimnairb** [comment]
@laurencelin Yes, I would think so.

**Comment by xiaoli-chen** [comment]
Brian,
     Thanks for finding these bugs.
     For the first issue, I don't know whether the local variable
rz_drainage and unsat_drainage will leads to accumulated invocations.

     In file patch_daily_F.c, line 1840 and line 1849, the rz_drainage is
defined and set to 0 or calculated by function
'compute_unsat_zone_drainage'. Before line 1840, model won't use
rz_drainage for drainage calculation. I think there may be some other
issues which makes the basinwise unsat-drainage 1-2 orders of magnitude
greater than they should be.

     For the second issue, I agree that it need to be Ksat_0_v
<https://github.com/RHESSys/RHESSys/blob/master/rhessys/cycle/patch_daily_F.c#L1849>
instead
of  Ksat_0.

     For the third issue, eh, I don't know... I really don't know why the
Ksat need to be divided by 2...

Best,
Xiaoli

On Mon, Jan 25, 2016 at 1:13 PM, Brian Miles <notifications@github.com>
wrote:

> In RHESSys 5.20.0, we are seeing basin-scale daily values of unsat and
> root zone drainage that are ~1-2 orders of magnitude greater than they
> should be. There appear to be a few problems with the calculation of
> unsaturated and/or root zone drainage.
>
> First, in patch_daily_F.c
> <https://github.com/RHESSys/RHESSys/blob/master/rhessys/cycle/patch_daily_F.c#L411>
> local variables *rz_drainage* and *unsat_drainage* are not initialized,
> which leads to cases where fluxes from a previous invocations can be
> accumulated and applied in subsequent invocations.
>
> Second, in some cases, root zone (and unsat) drainage is calculated using
> Ksat_0_v
> <https://github.com/RHESSys/RHESSys/blob/master/rhessys/cycle/patch_daily_F.c#L1849>,
> but in others using Ksat_0, as in here
> <https://github.com/RHESSys/RHESSys/blob/master/rhessys/cycle/patch_daily_F.c#L1879>,
> here
> <https://github.com/RHESSys/RHESSys/blob/master/rhessys/hydro/compute_subsurface_routing.c#L880>,
> and here
> <https://github.com/RHESSys/RHESSys/blob/master/rhessys/hydro/compute_subsurface_routing_hourly.c#L876>.
> It is not clear to me what is correct.
>
> Third, in the above examples the value of Ksat passed into
> *compute_unsat_zone_drainage()* are all divided by 2. Why is this done?
>
> I have a pending fix for the first problem, which I am testing now. I need
> advice on what the right thing to do is for the second. For the third, we
> need some text for the comments that describes the rationale for dividing
> Ksat by 2. I will address all three problems through a single branch and
> pull request that references this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RHESSys/RHESSys/issues/77>.
>



-- 
Xiaoli Chen

Bren School of Environmental Science and Management
University of California, Santa Barbara
xiaoli_chen@umail.ucsb.edu

**Comment by laurencelin** [comment]
Hello Brian and Xiaoli,

The divided by 2 and Ksat_0_v issues can be traced back to 5.18.r2 (see attached).  Additionally, I compared the “ compute_unsat_zone_drainage.c” in both 5.20 and 5.18, and they are the same. 
However, the extremely large unsat drainage and rz drainage are the problem in 5.20 and not in 5.18.

I am less familiar to rhessys hydrological flux calculation. what’s the use of “unsat drainage” in the model? this flux would affect patch.unsat.storage (line1860) but does it add to the GW storage or affect the sat_depth?

Laurence

**Comment by selimnairb** [comment]
@xiaoli-chen You are correct, the local variable was being initialized, so that is not the problem.

**Comment by selimnairb** [comment]
@laurencelin unsat storage goes into the saturated store, so it reduces sat_def.  I think we are seeing high unsat drainage because of a combination of low GW contribution to streamflow, as well as high Ksat values.

**Comment by selimnairb** [comment]
@xiaoli-chen I will fix the obvious problem with Ksat_0 needing to be Ksat_0_v in all cases.  Thanks for looking into this.

**Comment by madtraveller** [comment]
Hi everyone,

I think the factor "2" is to account for the typical ratio between Horizontal and Vertical hydraulic conductivity. But this anisotropy ratio really depends on soil/rock materials. In some cases can be as high as 100:1. Should this be a calibrated parameter instead of a hard coded number?

If the factor "2" is kept, I don't think we need to change from Ksat_0 to Ksat_0_v in all above mentioned files

References:
1. http://info.ngwa.org/gwol/pdf/881846057.PDF
2. http://www.aqtesolv.com/aquifer-tests/aquifer_properties.htm
3. http://www.brgs-la.org/web-content/22EDCF.pdf
4. http://onlinelibrary.wiley.com/doi/10.1029/97WR00570/pdf

**Comment by selimnairb** [comment]
@madtraveller Thanks for the follow up.  Whether we change from Ksat_0 to Ksat_0_v or not, the code should be consistent.  I will leave the divide by 2 for now, and will make Ksat consistent throughout.

**Comment by madtraveller** [comment]
@selimnairb I fully agree. And I think it's more intuitive to use Ksat_0 than Ksat_0_v in all compute_unsat_zone_drainage function calls if we're going to keep factor "2". Otherwise, we can:
1. Change everything to Ksat_0_v but remove factor "2" then
2. Define Ksat_0_v = Ksat_0 / 2 here 
https://github.com/RHESSys/RHESSys/blob/master/rhessys/init/construct_soil_defaults.c#L180

Tung

**Comment by selimnairb** [comment]
As per @naomitague The divide by two is done because the vertical fluxes are calculated before and after routing, and without the divide by two, the fluxes would be double counted.

**Comment by madtraveller** [comment]
Hi Brian,

If that's the case, shouldn't it be "compute_unsat_zone_drainage( ... ) / 2" rather than divide Ksat_0_v by 2 within that function?

Please correct me if I'm wrong, in https://github.com/RHESSys/RHESSys/blob/develop/rhessys/hydro/compute_unsat_zone_drainage.c#L99, Ksat_0 is used to find the min K_unsat between the value from the exponential decay curve and either Brooks & Corey or van Genuchten formulas. Then 

unsat_zone_drainage = max(min( potential_drainage,	Ksat ),0);

So if potential_drainage < Ksat, divide Ksat_0_v by 2 makes no difference. In fact, I did a quick test with my watershed for different cases: fix inconsistent Ksat_0 & Ksat_0_v; remove factor 2 etc. The results are almost identical (figure below)

![selection_057](https://cloud.githubusercontent.com/assets/6590141/13277788/4d425bfa-da80-11e5-94f9-b52b2cd235d5.png)

Tung

**Comment by selimnairb** [comment]
@naomitague Can you look at @madtraveller's note above and comment?

**Comment by naomitague** [comment]
Ok so here are my responses

1. Thanks Brian for catching the places where we were missing the "_v" - we should stay with
_v so that the user can differentiate between calibration of vertical and lateral conductivity and
use _v everywhere we are looking at vertical fluxes

2. Yes the /2 was to account for the fact that we need to call unsat-drainage twice - here and as part of lateral routing - However, I think the /2 should limit the rate  - if the rate (Ksat) is very high and all potential drainage occurs (even with the Ksat /2 that is fine - and we should allow this drainage before the routing

N

**Comment by selimnairb** [comment]
@tungmilan @naomitague  I am not sure if we should also make these changes to top_model.c as well as you mentioned in #80.  I am going to close this issue.  If such a change is needed, we should create a new issue and address it in develop and/or master through separate pull requests.
