### ISSUE TITLE
SIMULATION of RHESSys

### ISSUE THREAD

**Issue by rahul1525** [RHESSys/RHESSys#96]
Is the time taken to simulate streamflow depends on the size of the basin?

The thing is I am running a script to simulate runoff for the last 38 hours and is still running with no intend to finish, however the output file has some results inside it.
My basin area is about 770 sq. km and I am running for 10 months data.

Can anyone tell me what is going on and what is the possible solution to this as for further study I need to run it for many no. of years?

**Comment by jschoate** [comment]
How many patches in your model? look at the first line of your flowtable - it will be a single number on the first line. that will tell you how many patches you have. processing time will in large part depend on the number of patches you have (as well as, of course, processing power of the system you are running on).
remember - for each spatial unit, all of the internal RHESSys processing that occurs at that level must occur for each spatial unit of a given level.
for example, all of the internal processing that occurs at the patch level (i.e. soil & litter processing) must repeat for each patch spatial unit, all of the internal processing that occurs at the stratum level (i.e. vegetation C&N processing, growth) must repeat for each patch spatial unit, and if you set your zone level to the same spatial unit as the patch, then all the internal processing that occurs at the zone level (i.e. radiation, climate) must repeat for each spatial unit across the landscape.
therefore, the more patches you have, the more processing that must be done - so the more time it will take.

**Comment by rahul1525** [comment]
Thanks @jschoate, I have 788195 no. of patches and yes the zone level is set to be the same spatial unit as patch. Is there any way to reduce the no. of patch without reducing the resolution of dem (here in my case is 30 m, SRTM) or is there any work around so that I can run the model faster?

**Comment by rahul1525** [comment]
Thanks @jschoate <https://github.com/jschoate>, I have 788195 no. of
patches and yes the zone level is set to be the same spatial unit as patch.
Is there any way to reduce the no. of patch without reducing the resolution
of dem (here in my case is 30 m, SRTM) or is there any work around so that
I can run the model faster?

With regards
Waikhom Rahul Singh
SRF, NERIST
Arunachal Pradesh

**Comment by tungmilan** [comment]
@rahul1525 : you can modify RHESSys to run it in parallel mode per these commits. My 200-km2 watershed (30m DEM) took RHESSys approx. 2 hours for 15 years of daily simulation on 8-core HPC node. It was more than 32 hrs in serial mode 
https://github.com/tungmilan/RHESSys/commit/c6857492aa405563857926a61ef3ece4add3a266
https://github.com/tungmilan/RHESSys/commit/1f5112c7e10c75c1ef43354162bb4e0d1fe04f19
https://github.com/tungmilan/RHESSys/commit/bbc126f600c18da0162780230500da4dbf484a67

Hope this helps!

Tung

**Comment by rahul1525** [comment]
This is not quite related but

**Comment by rahul1525** [comment]
This is not quite related but I want the result so fast so Im dropping my doubts here.

After generating 500 sets of random numbers for 6 parameters, the calibration output generates 500 stream flow data. but all the sets are identical (means all set of stream flows say for 1 year time series are identical though within a set they are different).

Could anyone tell me where i went wrong?

**Comment by jschoate** [comment]
@rahul1525 - if you have confirmed that each RHESSys run is indeed running a different set of parameters on the respective command lines - then perhaps there is some issue with the set up of your script. 
if you are setting up the way we do in our lab, i.e.: simulation runs, streamflow is extracted from RHESSys output and written to a temporary streamflow file (tstrX), that temporary file gets added to the 'keeper' streamflow file (strX), the temporary streamflow file (tstrX) is deleted, then the next simulation runs & overwrites the output from the first simulation, streamflow extracted & new temporary streamflow file is created, etc....
then perhaps there is an issue with either consecutive simulation overwriting output from previous simulation, or the temporary streamflow file isn't being deleted and recreated each time, so that the first streamflow output just gets continuously added to the 'keeper' streamflow file.
if you think that this could be along the lines of you problem and you need assistance you can email me your script

**Comment by rahul1525** [comment]
May I get your mail ID

**Comment by jschoate** [comment]
jsc.eco@gmail.com
